// This file is transpiled by build.js

// @ts-ignore - build.js is generated by esbuild
import config from "./jen.config.js";
// @ts-ignore - build.js is generated by esbuild
import { buildSite } from "./src/build/build.js";

await buildSite({
  config
});
