[package]
name = "jen_launcher"
version = "0.2.0"
edition = "2021"
description = "Tiny Node.js launcher"
license = "MIT"
repository = "https://github.com/oopsio/jen.js/tree/main/crates/cli"
readme = "README.md"

[dependencies]
tokio = { version = "1", features = ["full"] }

[profile.release]
# Strips debug info, optimizes for size
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true