/*
 * Build script for Jen.js blog example
 */

import { execSync } from "node:child_process";

// Generate posts data from markdown files first
console.log("[BUILD] Generating posts...");
execSync("node -r tsx/esm scripts/generate-posts.ts", { stdio: "inherit" });

// @ts-ignore - build.js is generated by esbuild
import { buildSite } from "./lib/build/build.js";
// @ts-ignore
import config from "./jen.config.ts";

console.log("[BUILD] Building site...");
await buildSite({
  config,
});
