name: Build Jen CLI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # macOS
          - os: macos
            runner: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos
            runner: macos-latest
            rust_target: aarch64-apple-darwin

          # Linux
          - os: linux
            runner: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - os: linux
            runner: ubuntu-latest
            rust_target: i686-unknown-linux-gnu
          - os: linux
            runner: ubuntu-latest
            rust_target: aarch64-unknown-linux-gnu

          # Windows
          - os: windows
            runner: windows-latest
            rust_target: x86_64-pc-windows-msvc
          - os: windows
            runner: windows-latest
            rust_target: i686-pc-windows-msvc

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add target
        run: rustup target add ${{ matrix.rust_target }}

      - name: Create build folder
        run: mkdir -p build

      - name: Build Jen CLI
        shell: bash
        run: |
          BIN_NAME=jen-${{ matrix.os }}-${{ matrix.rust_target }}
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            BIN_NAME=${BIN_NAME}.exe
          fi
          cargo build --release --target ${{ matrix.rust_target }}
          cp target/${{ matrix.rust_target }}/release/jen build/$BIN_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jen-${{ matrix.os }}-${{ matrix.rust_target }}
          path: build/*
